const USERS_KEY='smartpark_users', BOOKINGS_KEY='smartpark_bookings', CURRENT_KEY='smartpark_current';
const defaultUsers=[{name:'Demo User',email:'demo@smartpark.com',password:'123456'}];
const defaultBookings=[{id:'BK1001',slot:'A1',vehicle:'MH12AB1234',date:'2026-08-29',start:'10:00',end:'12:00',amount:100,email:'demo@smartpark.com',status:'Confirmed'}];
const slots=['A1','A2','A3','A4','B1','B2','B3','B4','C1','C2','C3','C4'];
function getUsers(){return JSON.parse(localStorage.getItem(USERS_KEY)||JSON.stringify(defaultUsers))}function saveUsers(x){localStorage.setItem(USERS_KEY,JSON.stringify(x))}function getBookings(){return JSON.parse(localStorage.getItem(BOOKINGS_KEY)||JSON.stringify(defaultBookings))}function saveBookings(x){localStorage.setItem(BOOKINGS_KEY,JSON.stringify(x))}function current(){return localStorage.getItem(CURRENT_KEY)}
function nav(){const el=document.querySelector('.navlinks');if(!el)return;const logged=!!current();el.innerHTML=`<a href="index.html">Home</a><a href="parking.html">Parking</a><a href="contact.html">Contact</a>${logged?'<a href="bookings.html">My Bookings</a>':'<a href="login.html">Login</a>'}${logged?'<button class="btn btn-green" onclick="logout()">Logout</button>':''}`}
function logout(){localStorage.removeItem(CURRENT_KEY);location.href='index.html'}
function requireLogin(){if(!current()){location.href='login.html';return false}return true}
function initLogin(){const f=document.getElementById('loginForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();const email=document.getElementById('email').value.trim().toLowerCase(),pass=document.getElementById('password').value;const u=getUsers().find(x=>x.email===email&&x.password===pass);if(!u){document.getElementById('msg').textContent='Invalid email or password.';return}localStorage.setItem(CURRENT_KEY,email);location.href='parking.html'}}
function initRegister(){const f=document.getElementById('registerForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();const name=document.getElementById('name').value.trim(),email=document.getElementById('email').value.trim().toLowerCase(),pass=document.getElementById('password').value,confirm=document.getElementById('confirm').value;if(pass!==confirm){document.getElementById('msg').textContent='Passwords do not match.';return}let users=getUsers();if(users.some(x=>x.email===email)){document.getElementById('msg').textContent='Account already exists.';return}users.push({name,email,password:pass});saveUsers(users);localStorage.setItem(CURRENT_KEY,email);location.href='parking.html'}}
function renderSlots(){const grid=document.getElementById('slotGrid');if(!grid)return;const bookings=getBookings();const occupied=new Set(bookings.filter(b=>b.date===new Date().toISOString().slice(0,10)&&b.status!=='Cancelled').map(b=>b.slot));grid.innerHTML=slots.map(s=>occupied.has(s)?`<div class="slot occupied"><h3>${s}</h3><p>Occupied</p></div>`:`<div class="slot available"><h3>${s}</h3><p>Available</p><button onclick="bookSlot('${s}')">Book Now</button></div>`).join('')}
function bookSlot(slot){if(!requireLogin())return;location.href='booking.html?slot='+encodeURIComponent(slot)}
function initBooking(){if(!document.getElementById('bookingForm'))return;if(!requireLogin())return;const slot=new URLSearchParams(location.search).get('slot')||'A1';document.getElementById('slot').textContent=slot;document.getElementById('slotInput').value=slot;const f=document.getElementById('bookingForm');f.onsubmit=e=>{e.preventDefault();const vehicle=document.getElementById('vehicle').value.trim(),date=document.getElementById('date').value,start=document.getElementById('start').value,end=document.getElementById('end').value;if(!vehicle||!date||!start||!end){document.getElementById('msg').textContent='Please fill all fields.';return}if(end<=start){document.getElementById('msg').textContent='End time must be after start time.';return}const amount=Math.max(1,(parseInt(end.split(':')[0])*60+parseInt(end.split(':')[1])-(parseInt(start.split(':')[0])*60+parseInt(start.split(':')[1])))/60)*50;const b={id:'BK'+Date.now().toString().slice(-6),slot,vehicle,date,start,end,amount:Math.round(amount),email:current(),status:'Confirmed'};let arr=getBookings();arr.push(b);saveBookings(arr);localStorage.setItem('smartpark_last_booking',JSON.stringify(b));location.href='confirmation.html'}}
function initConfirmation(){const box=document.getElementById('confirmation');if(!box)return;const b=JSON.parse(localStorage.getItem('smartpark_last_booking')||'null');if(!b){box.innerHTML='<p>No recent booking found.</p>';return}box.innerHTML=`<div class="check">✓</div><h2>Booking Confirmed!</h2><p>Your parking slot has been successfully booked.</p><div class="card" style="text-align:left;margin:25px 0"><div class="summary-row"><b>Booking ID</b><span>${b.id}</span></div><div class="summary-row"><b>Slot Number</b><span>${b.slot}</span></div><div class="summary-row"><b>Vehicle Number</b><span>${b.vehicle}</span></div><div class="summary-row"><b>Date</b><span>${b.date}</span></div><div class="summary-row"><b>Time</b><span>${b.start} - ${b.end}</span></div><div class="summary-row"><b>Amount Paid</b><span>₹${b.amount}</span></div></div><a class="btn btn-blue" href="bookings.html">View My Bookings</a> <a class="btn btn-outline" href="index.html">Back to Home</a>`}
function initBookings(){const table=document.getElementById('bookingRows');if(!table)return;if(!requireLogin())return;const arr=getBookings().filter(b=>b.email===current());table.innerHTML=arr.length?arr.map(b=>`<tr><td>${b.id}</td><td>${b.slot}</td><td>${b.vehicle}</td><td>${b.date}</td><td>${b.start} - ${b.end}</td><td>₹${b.amount}</td><td class="status">${b.status}</td><td>${b.status==='Confirmed'?`<button class="btn-danger" onclick="cancelBooking('${b.id}')">Cancel</button>`:'-'}</td></tr>`).join(''):'<tr><td colspan="8" style="text-align:center">No bookings yet.</td></tr>'}
function cancelBooking(id){let arr=getBookings();arr=arr.map(b=>b.id===id?{...b,status:'Cancelled'}:b);saveBookings(arr);initBookings();}
function initAdmin(){const rows=document.getElementById('adminRows');if(!rows)return;const arr=getBookings();document.getElementById('totalSlots').textContent=slots.length;document.getElementById('availableSlots').textContent=slots.length-new Set(arr.filter(b=>b.status==='Confirmed'&&b.date===new Date().toISOString().slice(0,10)).map(b=>b.slot)).size;document.getElementById('occupiedSlots').textContent=slots.length-Number(document.getElementById('availableSlots').textContent);document.getElementById('totalBookings').textContent=arr.length;rows.innerHTML=arr.slice().reverse().map(b=>`<tr><td>${b.id}</td><td>${b.email}</td><td>${b.slot}</td><td>${b.vehicle}</td><td>${b.date}</td><td>${b.start}-${b.end}</td><td class="status">${b.status}</td></tr>`).join('')}
document.addEventListener('DOMContentLoaded',()=>{nav();initLogin();initRegister();renderSlots();initBooking();initConfirmation();initBookings();initAdmin();});
